# Generated by Django 2.2.16 on 2022-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='12345', max_length=128, verbose_name='Пароль'),
        ),
    ]
