# Generated by Django 2.2.16 on 2022-10-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_remove_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('genre__slug',), 'verbose_name': 'Произведение'},
        ),
    ]
